version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5900

    expose: 
     - "5900"
     
          
  firefox:
    image: selenium/node-firefox-debug:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5900

    expose: 
     - "5900"